; 车库门智能控制器 P0
; ESP32 Dev Module / WROOM32, COM3 (CP2102)
; 使用经典蓝牙(BluetoothSerial)搜索手机/车机 + WiFi SoftAP

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
upload_port = COM3
monitor_port = COM3
board_build.partitions = huge_app.csv

build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DBOARD_HAS_PSRAM=0

lib_deps =

monitor_filters = esp32_exception_decoder, time
